/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from "./MockERC20";
export type { MockToken } from "./MockToken";
export type { MockTokenV2 } from "./MockTokenV2";
